### ISSUE TITLE
TypeError: Cannot read property 'public_interfaces' of undefined

### ISSUE THREAD

**Issue by EricCat** [bipio-server/bipio#45]
I used ``git clone https://github.com/bipio-server/bipio.git`` and then ``make install``.
When I run ``$ node src/server.js``. I got the error: ``TypeError: Cannot read property 'public_interfaces' of undefined``. 

TraceInfo:
```
    at Object.<anonymous> (node_modules/bipio/src/bootstrap.js:158:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (node_modules/bipio/src/server.js:23:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by mjpearson** [comment]
Hi, that happens when make install fails to complete - you should get an interactive setup and it should confirm that config has been written during 'make install'.

Install will fail if any npm dependencies failed to download.  From the bipio server directory try 'rm -rf node_modules; make install' to retry.

did you notice any errors during setup?

**Comment by EricCat** [comment]
Thanks @mjackson .
1. I'm now using non-interactive setup.
2. my config is:
```
export NODE_CONFIG_DIR=data/etc
export NODE_DATA_DIR=data/var
export HEADLESS=true
```
3. I tried 5 times for catch any npm dependencies failed, but there is non-failed. all install successfully.

**Comment by EricCat** [comment]
@mjackson  Also I found if using non-interactive setup: ``export HEADLESS=true``,
``npm install bipio`` or ``npm install -g bipio`` also report the same error
