### ISSUE TITLE
Error in account_options during server installation

### ISSUE THREAD

**Issue by Sinisterwing** [bipio-server/bipio#67]
Recently downloaded and installed a local bipio server instance. The server started up correctly and visiting localhost:5000/status indicated that all connections were working. However, I failed to mount the server on bip.io. Likewise, requests to localhost:5000/login failed, as well as attempts to manually POST bips to the server via a REST client. 

A bit of digging revealed that the server was complaining about a missing entry in the account_options collection on the bipio database. The collection was completely empty. A reinstall of the server allowed me to catch these errors during installation:

Trace: Caught exception: TypeError: this.getAccountInfo(...).testDomain is not a function
TypeError: this.getAccountInfo(...).testDomain is not a function
    at model.AccountOption.entitySchema.bip_domain_id.validate.validator (/home/mark/bipio/src/models/account_option.js:150:43)
    at /home/mark/bipio/node_modules/mongoose/lib/schematype.js:686:19
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/home/mark/bipio/node_modules/mongoose/lib/schematype.js:667:19)
    at /home/mark/bipio/node_modules/mongoose/lib/document.js:1133:9
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
    at Object.app.logmessage (/home/mark/bipio/src/bootstrap.js:192:15)
    at process.<anonymous> (/home/mark/bipio/src/bootstrap.js:255:9)
    at emitOne (events.js:82:20)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:223:26)
Trace: WORKER:PID:5378:1453918898640:Caught exception: TypeError: this.getAccountInfo(...).testDomain is not a function
TypeError: this.getAccountInfo(...).testDomain is not a function
    at model.AccountOption.entitySchema.bip_domain_id.validate.validator (/home/mark/bipio/src/models/account_option.js:150:43)
    at /home/mark/bipio/node_modules/mongoose/lib/schematype.js:686:19
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/home/mark/bipio/node_modules/mongoose/lib/schematype.js:667:19)
    at /home/mark/bipio/node_modules/mongoose/lib/document.js:1133:9
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
    at Object.app.logmessage (/home/mark/bipio/src/bootstrap.js:210:14)
    at process.<anonymous> (/home/mark/bipio/src/bootstrap.js:255:9)
    at emitOne (events.js:82:20)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:223:26)

This appears to be an issue with the latest commit. Please look into this. Thank you in advance.

**Comment by r4nm4** [comment]
Hi,
I have the same issue as well, so I'm unable to setup bipio server :(
Can anyone have a look at this issue? It's been 3 months already since the previous guy posted.
Thanks!

**Comment by r4nm4** [comment]
I fixed this issue by rolling back the changes happened on 15 Dec 2015 on src/models/account_option.js file

https://github.com/bipio-server/bipio/commit/00736141eedd62a370b0a6db52cc5b4bb2de464b
